import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import GlobalNav from '@/components/GlobalNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mercave',
  description: 'Generated by ADIF',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNav>
          {children}
        </GlobalNav>
      </body>
    </html>
  )
}
